config/routes.rb
Rails.application.routes.draw do
  root to: 'main#home'

  get 'main/categories'

  get 'main/products'

  get 'main/details'

  get 'main/panier'

  get 'main/geo'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :categories, :products, :details, :panier, :geo]

  def home
  end

  def categories
  end

  def products
  end

  def details
  end

  def panier
  end

  def geo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Easylist</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/main/categories.html.erb
<div class="container">
  <div class="row ">
    <div class="col-xs-12 col-sm-6 push">
      <input class="form-control" type="search" placeholder="Example input">
        <fieldset class="form-group">
          <label for="search-1">Entrer:</label>
            <input type="checkbox" id="search-1" >
          <label for="search-2">Plat:</label>
            <input type="checkbox"  id="search-2">
          <label for="search-3">Dessert:</label>
            <input type="checkbox" id="search-3">
        </fieldset>
    </div>
  </div><!-- /.row -->
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Some stuff</h2>
          <p>Very cool stuff, useful and smart</p>
        </div>
        <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
        <%= link_to "", main_products_url , class: "card-link"  %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Some stuff</h2>
          <p>Very cool stuff, useful and smart</p>
        </div>
        <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
        <%= link_to "", main_products_url , class: "card-link"  %>
      </div>
    </div>
  </div>
  <div class="row air">
    <div class="col-xs-12 col-sm-6">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Some stuff</h2>
          <p>Very cool stuff, useful and smart</p>
        </div>
        <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
        <%= link_to "", main_products_url , class: "card-link"  %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Some stuff</h2>
          <p>Very cool stuff, useful and smart</p>
        </div>
        <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
        <%= link_to "", main_products_url , class: "card-link"  %>
      </div>
    </div>
  </div>
</div>

app/views/main/details.html.erb
<div class="container">
  <div class="row">
    <aside class="col-xs-12 col-sm-3">
    <%= link_to "retour au resultats", main_products_url , class: "fa fa-long-arrow-left fa-2x pad-link"  %>
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
        <div class="card-category">Popular</div>
        <div class="card-description">
          <h2>Some stuff</h2>
          <p>Very cool stuff, useful and smart</p>
        </div>
        <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
        <%= link_to "", main_details_url , class: "card-link"  %>
      </div>
      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Panel heading</div>
        <div class="panel-body">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
          </p>
        </div>
        <!-- List group -->
        <ul class="list-group">
          <li class="list-group-item">Cras justo odio</li>
          <li class="list-group-item">Dapibus ac facilisis in</li>
          <li class="list-group-item">Morbi leo risus</li>
          <li class="list-group-item">Porta ac consectetur ac</li>
          <li class="list-group-item">Vestibulum at eros</li>
        </ul>
      </div>
     </aside>
     <article class="col-xs-12 col-sm-8 text-center">
      <h1 class="ico-marg">Lasagne au cheval</h1>
      <div class="ico-marg">
        <i class="fa fa-clock-o fa-1x" aria-hidden="true"> 10 min</i>
        <i class="fa fa-cutlery fa-1x" aria-hidden="true"> 4 personnes</i>
        <i class="fa fa-lemon-o fa-1x" aria-hidden="true"> a base de cannasson </i>
      </div>
      <div>
     <%= link_to  main_panier_url do   %>
       <button type="button" class="btn btn-default btn-lg">
          <span class="fa fa-cart-arrow-down" aria-hidden="true"></span> Ajouter au panier
        </button>
        <% end %>
         <button type="button" class="btn btn-default btn-lg">
          <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Ajouter au favoris
        </button>
      </div>
      <ul>
        <li class="fa fa-angellist text-left li-pad" aria-hidden="true"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
        <li class="fa fa-angellist text-left li-pad" aria-hidden="true"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
        <li class="fa fa-angellist text-left li-pad" aria-hidden="true"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
        <li class="fa fa-angellist text-left li-pad" aria-hidden="true"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
        <li class="fa fa-angellist text-left li-pad" aria-hidden="true"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</li>
      </ul>
     </article>

  </div>
</div>

app/views/main/geo.html.erb
<div class="container">
  <div class="row">
  <div class="my" >My</div> <%= image_tag  "negro.svg", {class: "panier-tails"} %>
    <div class="col-xs-12 col-sm-4">
      <div class="jumbotron">
        <div class="line-air">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
          <div class="card-category">Popular</div>
          <div class="card-description">
            <h2>Some stuff</h2>
            <p>Very cool stuff, useful and smart</p>
          </div>
          <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
          <%= link_to "", main_details_url , class: "card-link"  %>
        </div>
      </div>
      <div class="line-air">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
          <div class="card-category">Popular</div>
          <div class="card-description">
            <h2>Some stuff</h2>
            <p>Very cool stuff, useful and smart</p>
          </div>
          <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
          <%= link_to "", main_details_url , class: "card-link"  %>
        </div>
      </div>
      <div class="line-air">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
          <div class="card-category">Popular</div>
          <div class="card-description">
            <h2>Some stuff</h2>
            <p>Very cool stuff, useful and smart</p>
          </div>
          <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
          <%= link_to "", main_details_url , class: "card-link"  %>
        </div>
      </div>
      <div class="line-air">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
          <div class="card-category">Popular</div>
          <div class="card-description">
            <h2>Some stuff</h2>
            <p>Very cool stuff, useful and smart</p>
          </div>
          <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
          <%= link_to "", main_details_url , class: "card-link"  %>
        </div>
      </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-8">
        <div id="map"></div>
      <script>




      // This example displays a marker at the center of Australia.
      // When the user clicks the marker, an info window opens.

      function initMap() {
        var uluru = {lat: 43.294825, lng: 5.37446};
        var de = {lat: 43.296789, lng: 5.37446};
        var es = {lat: 43.294825, lng: 5.38234};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: uluru
        });

        var contentString = '<div id="content">'+
            '<div id="siteNotice">'+
            '</div>'+
            '<h1 id="firstHeading" class="firstHeading">Marseille</h1>'+
            '<iframe width="560" height="315" src="https://www.youtube.com/embed/Tw28Fvl4OPo?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>'+
            '</div>'+
            '</div>';

        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });

        var marker = new google.maps.Marker({
          position: uluru,
          map: map,
          title: 'Uluru (Ayers Rock)'
        });
        var marke = new google.maps.Marker({
          icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
          position: de,
          map: map,
          title: 'Uluru (Ayers Rock)'
        });
        var mark = new google.maps.Marker({
          icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png',
          position: es,
          map: map,
          title: 'Uluru (Ayers Rock)'
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });
      }
    </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDjDpAFJl9z4E-deyYyQK_Zv6vGlmS4gTk&callback=initMap"
      async defer></script>
    </div>
  </div>
</div>

<style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        width: 100%;
        height: 100%;
        margin-top: 10%;
        background-color: grey;
      }
      /* Optional: Makes the sample page fill the window. */
      /*html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }*/
    </style>

app/views/main/home.html.erb
<div class="container">
  <div class="row text-center">
    <span>Easylist</span>
    <h1>Vos courses en 10 minutes</h1>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
            <div class="card-category">Popular</div>
            <div class="card-description">
              <h2>Some stuff</h2>
              <p>Very cool stuff, useful and smart</p>
            </div>
            <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
            <!-- <a class="card-link" href="#" ></a> -->
            <%= link_to "", main_categories_url , class: "card-link"  %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
            <div class="card-category">Popular</div>
            <div class="card-description">
              <h2>Some stuff</h2>
              <p>Very cool stuff, useful and smart</p>
            </div>
            <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
            <!-- <a class="card-link" href="#" ></a> -->
            <%= link_to "", main_categories_url , class: "card-link"  %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://unsplash.it/200/300/?random');">
            <div class="card-category">Popular</div>
            <div class="card-description">
              <h2>Some stuff</h2>
              <p>Very cool stuff, useful and smart</p>
            </div>
            <img class="card-user avatar" src="https://unsplash.it/200/300/?random">
            <%= link_to "", main_categories_url , class: "card-link"  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/main/panier.html.erb
<div class="container">
  <div class="row">
    <div class="my" >My</div> <%= image_tag  "negro.svg", {class: "panier-tails"} %>
    <div class="text-center">
      <i class="fa fa-download fa-2x ico-pad" aria-hidden="true"></i>
      <i class="fa fa-file-pdf-o fa-2x ico-pad" aria-hidden="true"></i>
    </div>
    <div class="col-xs-12 col-sm-offset-1 col-sm-8">
        <h2>RAYON FRAIS</h2>
        <ul class="list-unstyled">
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
        </ul>
        <h2>RAYON FRAIS</h2>
        <ul class="list-unstyled">
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
        </ul>
        <h2>RAYON FRAIS</h2>
        <ul class="list-unstyled">
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
          <li><i class="fa fa-minus" aria-hidden="true"></i><span> 1 </span><i class="fa fa-plus" aria-hidden="true">        <span>        Lorem ipsum </span> </i> <i class="fa fa-trash-o" aria-hidden="true"></i></li>
        </ul>
    </div>
    <div class="col-xs-12 col-sm-3">
    <h3>Total panier</h3>
    <h3>30 €</h3>
      <ul class="list-unstyled label-config">
        <li>
          <div class="has-warning">
            <div class="checkbox">
              <label>
                <input type="checkbox" id="checkboxWarning" value="option1">
                 Economique
              </label>
            </div>
          </div>
        </li>
        <li>
          <div class="has-warning">
            <div class="checkbox">
              <label>
                <input type="checkbox" id="checkboxWarning" value="option1">
                 Rapport qualiter / prix
              </label>
            </div>
          </div>
        </li>
        <li>
          <div class="has-warning">
            <div class="checkbox">
              <label>
                <input type="checkbox" id="checkboxWarning" value="option1">
                 Premium
              </label>
            </div>
          </div>
        </li>
        <li>
          <div class="has-warning">
            <div class="checkbox">
              <label>
                <input type="checkbox" id="checkboxWarning" value="option1">
                 Bio
              </label>
            </div>
          </div>
        </li>
        <li>
          <div class="has-warning">
            <div class="checkbox">
              <label>
                <input type="checkbox" id="checkboxWarning" value="option1">
                 Sans gluten
              </label>
            </div>
          </div>
        </li>
        <li>
          <div class="has-warning">
            <div class="checkbox">
              <label>
                <input type="checkbox" id="checkboxWarning" value="option1">
                 Halal
              </label>
            </div>
          </div>
        </li>
        <li>
          <div class="has-warning">
            <div class="checkbox">
              <label>
                <input type="checkbox" id="checkboxWarning" value="option1">
                 Casher
              </label>
            </div>
          </div>
        </li>
        <li>
        <%= link_to  main_geo_url do %>
          <button type="button" class="btn btn-warning">
          Trouver un marchant
          </button>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>